Simple websocket server
CoolStory-Studio/coolstory-gram-server pull request #17
Opened 2023-08-20 09:10 UTC by cadnev

Closes #14.

2023-09-06 13:25 UTC, temikfart requested changes
Mostly codestyle issues, but not all.

2023-09-06 13:25 UTC, temikfart commented on include/CSGServer/websocket_session.hpp
> +void run(net::ip::address address, unsigned short port, int threads);
Add new empty line at the end of the file.

2023-09-06 13:25 UTC, temikfart commented on src/main.cpp
> +    // Check command line arguments.
This is an extra comment. Do not write comments like this one, if it's a simple thing in code.

2023-09-06 13:25 UTC, temikfart commented on src/main.cpp
> +    {
According to [Codestyle](https://github.com/CoolStory-Studio/coolstory-gram/discussions/2), the curly brace must be in the same line as the operator `if`.

2023-09-06 13:25 UTC, temikfart commented on src/main.cpp
> +        return EXIT_SUCCESS;
`EXIT_FAILURE` more preferable.

2023-09-06 13:25 UTC, temikfart commented on src/main.cpp
> +    auto const port = static_cast<unsigned short>(std::atoi(argv[2]));
Not for changes: _If you don't have any specific cause to use unusual type, than use `int`._

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +    if(ec)
Spaces!

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +    {
Spaces!

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +        if(ec == websocket::error::closed) {
Spaces!

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +        if(ec)
Spaces!

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +        if(ec)
Spaces!

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +    if(ec)
Spaces!

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +        if(ec)
Spaces!

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +                            std::placeholders::_1));
`else` branch must be with curly braces or fix tabulation.

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +                });
put code in `for` body using curly braces.

2023-09-06 13:25 UTC, temikfart commented on src/websocket_session.cpp
> +                });
And fix spacing.

2023-09-06 13:26 UTC, temikfart commented on src/websocket_session.cpp
> +}
Does this function should do `exit()`?

2023-09-22 16:05 UTC, cann3v commented on src/websocket_session.cpp
> +}
No, it doesn't. When the application is serving the client, an error may occur (connection, read/write websocket etc). In this case, the connection with client is closed, but the application continues to serve other clients.

2023-09-25 15:34 UTC, temikfart approved these changes

2023-09-25 15:42 UTC, merged